/**
 * STAT_META - Complete stat dictionary for all positions
 * Defines: label, better direction, format, football concept, description
 */

export const STAT_META = {
  QB: {
    completions_pct: {
      label: "Completion %",
      better: "higher",
      format: "pct1",
      concept: "Accuracy",
      description: "Percentage of passes completed",
    },
    cpoe: {
      label: "CPOE",
      better: "higher",
      format: "pct1",
      concept: "Accuracy vs Expectation",
      description: "Completion % above expected",
    },
    pass_epa: {
      label: "Pass EPA",
      better: "higher",
      format: "float2",
      concept: "Efficiency",
      description: "Expected points added per pass",
    },
    pacr: {
      label: "PACR",
      better: "higher",
      format: "float2",
      concept: "Aggression",
      description: "Passing yards per air yard",
    },
    pass_yards: {
      label: "Pass Yards",
      better: "higher",
      format: "int",
      concept: "Volume",
      description: "Total passing yards",
    },
    pass_tds: {
      label: "Pass TDs",
      better: "higher",
      format: "int",
      concept: "Scoring",
      description: "Passing touchdowns",
    },
    interceptions: {
      label: "Interceptions",
      better: "lower",
      format: "int",
      concept: "Risk Control",
      description: "Passes intercepted",
    },
    rush_yards: {
      label: "Rush Yards",
      better: "higher",
      format: "int",
      concept: "Mobility",
      description: "Rushing yards on ground",
    },
    rush_tds: {
      label: "Rush TDs",
      better: "higher",
      format: "int",
      concept: "Mobility Scoring",
      description: "Rushing touchdowns",
    },
    qbr_total: {
      label: "QBR",
      better: "higher",
      format: "float1",
      concept: "Overall Rating",
      description: "Quarter Back Rating (0-100)",
    },
    crunch_time_grade: {
      label: "Crunch Time Grade",
      better: "higher",
      format: "pct1",
      concept: "Clutch Performance",
      description: "Performance in high-pressure moments",
    },
  },
  RB: {
    rush_yards: {
      label: "Rush Yards",
      better: "higher",
      format: "int",
      concept: "Rushing Volume",
      description: "Rushing yards",
    },
    rush_tds: {
      label: "Rush TDs",
      better: "higher",
      format: "int",
      concept: "Rushing Scoring",
      description: "Rushing touchdowns",
    },
    rec_yards: {
      label: "Rec Yards",
      better: "higher",
      format: "int",
      concept: "Receiving Role",
      description: "Receiving yards",
    },
    rec_tds: {
      label: "Rec TDs",
      better: "higher",
      format: "int",
      concept: "Receiving Scoring",
      description: "Receiving touchdowns",
    },
    rec_yac: {
      label: "YAC",
      better: "higher",
      format: "float1",
      concept: "After-Catch Ability",
      description: "Yards after catch per reception",
    },
    receptions: {
      label: "Receptions",
      better: "higher",
      format: "int",
      concept: "Usage",
      description: "Total receptions",
    },
    carries: {
      label: "Carries",
      better: "higher",
      format: "int",
      concept: "Workload",
      description: "Rushing attempts",
    },
    crunch_time_grade: {
      label: "Crunch Time Grade",
      better: "higher",
      format: "pct1",
      concept: "Clutch Performance",
      description: "Performance in high-pressure moments",
    },
  },
  WR: {
    rec_yards: {
      label: "Rec Yards",
      better: "higher",
      format: "int",
      concept: "Receiving Volume",
      description: "Receiving yards",
    },
    rec_tds: {
      label: "Rec TDs",
      better: "higher",
      format: "int",
      concept: "Red Zone Scoring",
      description: "Receiving touchdowns",
    },
    receptions: {
      label: "Receptions",
      better: "higher",
      format: "int",
      concept: "Usage",
      description: "Total receptions",
    },
    targets: {
      label: "Targets",
      better: "higher",
      format: "int",
      concept: "Volume Share",
      description: "Pass targets",
    },
    rec_yac: {
      label: "YAC",
      better: "higher",
      format: "float1",
      concept: "After-Catch Ability",
      description: "Yards after catch",
    },
    target_share: {
      label: "Target Share",
      better: "higher",
      format: "pct1",
      concept: "Usage Rate",
      description: "Percentage of team targets",
    },
    wopr: {
      label: "WOPR",
      better: "higher",
      format: "float2",
      concept: "Opportunity Rating",
      description: "Weighted opportunity rating",
    },
    crunch_time_grade: {
      label: "Crunch Time Grade",
      better: "higher",
      format: "pct1",
      concept: "Clutch Performance",
      description: "Performance in high-pressure moments",
    },
  },
  DB: {
    solo_tackles: {
      label: "Solo Tackles",
      better: "higher",
      format: "int",
      concept: "Tackling Volume",
      description: "Solo tackles",
    },
    passes_defended: {
      label: "Passes Defended",
      better: "higher",
      format: "int",
      concept: "Coverage Skill",
      description: "Passes deflected or intercepted",
    },
    tackles_for_loss: {
      label: "TFL",
      better: "higher",
      format: "int",
      concept: "Disruption",
      description: "Tackles for loss",
    },
    fumbles_forced: {
      label: "Forced Fumbles",
      better: "higher",
      format: "int",
      concept: "Ball Disruption",
      description: "Fumbles forced",
    },
    qb_hits: {
      label: "QB Hits",
      better: "higher",
      format: "int",
      concept: "Pass Disruption",
      description: "Quarterback hits",
    },
    crunch_time_grade: {
      label: "Crunch Time Grade",
      better: "higher",
      format: "pct1",
      concept: "Clutch Performance",
      description: "Performance in high-pressure moments",
    },
  },
};

/**
 * Normalization bounds for each stat
 * Used to scale raw values to 0-1 range
 * Based on 2025 season league-wide data
 */
export const STAT_BOUNDS = {
  QB: {
    completions_pct: { min: 50, max: 75 },
    cpoe: { min: -5, max: 10 },
    pass_epa: { min: -0.3, max: 0.5 },
    pacr: { min: 0.8, max: 1.5 },
    pass_yards: { min: 2000, max: 5000 },
    pass_tds: { min: 10, max: 50 },
    interceptions: { min: 0, max: 20 },
    rush_yards: { min: 50, max: 600 },
    rush_tds: { min: 0, max: 10 },
    qbr_total: { min: 30, max: 80 },
    crunch_time_grade: { min: 40, max: 90 },
  },
  RB: {
    rush_yards: { min: 500, max: 1500 },
    rush_tds: { min: 0, max: 15 },
    rec_yards: { min: 100, max: 800 },
    rec_tds: { min: 0, max: 8 },
    rec_yac: { min: 4, max: 7 },
    receptions: { min: 20, max: 100 },
    carries: { min: 100, max: 400 },
    crunch_time_grade: { min: 40, max: 90 },
  },
  WR: {
    rec_yards: { min: 400, max: 1900 },
    rec_tds: { min: 0, max: 15 },
    receptions: { min: 30, max: 150 },
    targets: { min: 50, max: 200 },
    rec_yac: { min: 4, max: 7 },
    target_share: { min: 10, max: 35 },
    wopr: { min: 0.1, max: 0.4 },
    crunch_time_grade: { min: 40, max: 90 },
  },
  DB: {
    solo_tackles: { min: 20, max: 100 },
    passes_defended: { min: 3, max: 20 },
    tackles_for_loss: { min: 1, max: 15 },
    fumbles_forced: { min: 0, max: 5 },
    qb_hits: { min: 2, max: 20 },
    crunch_time_grade: { min: 40, max: 90 },
  },
};
