export const STAT_DISPLAY_NAMES = {
  // Common Stats
  crunch_time_grade: "Crunch Time Grade",
  completions_pct: "Completion Percentage",
  fantasy_points: "Fantasy Points",

  // QB Stats
  completions: "Completions",
  attempts: "Pass Attempts",
  pass_yards: "Passing Yards",
  pass_tds: "Passing Touchdowns",
  interceptions: "Interceptions",
  sacks: "Sacks",
  pass_epa: "Passing EPA",
  rush_yards: "Rushing Yards",
  rush_tds: "Rushing Touchdowns",
  rush_epa: "Rushing EPA",
  fumbles_lost: "Fumbles Lost",
  cpoe: "CPOE",
  pacr: "PACR",
  qbr_total: "QBR",
  qbr_epa_total: "EPA Total",

  // RB Stats
  carries: "Carries",
  rush_yards: "Rushing Yards",
  rush_tds: "Rushing Touchdowns",
  rush_fumbles: "Rushing Fumbles",
  receptions: "Receptions",
  rec_yards: "Receiving Yards",
  rec_tds: "Receiving Touchdowns",
  rec_fumbles: "Receiving Fumbles",
  rec_yac: "Yards After Catch",

  // WR/TE Stats
  targets: "Targets",
  rec_epa: "Receiving EPA",
  racr: "RACR",
  target_share: "Target Share %",
  air_yards_share: "Air Yards Share %",
  wopr: "WOPR",

  // DB Stats
  solo_tackles: "Solo Tackles",
  assisted_tackles: "Assisted Tackles",
  tackles_with_assist: "Tackles with Assist",
  tackles_for_loss: "Tackles for Loss",
  fumbles_forced: "Forced Fumbles",
  qb_hits: "QB Hits",
  passes_defended: "Passes Defended",
  defensive_tds: "Defensive Touchdowns",
  penalties: "Penalties",
  total_tackles: "Total Tackles"
};

export const BETTER_DIRECTION = {
  interceptions: "lower",          // QB stat
  sacks: "lower",
  fumbles_lost: "lower",
  rush_fumbles: "lower",
  rec_fumbles: "lower",
  penalties: "lower"
};

// Define stat order for each position (matches normalize.js order)
export const STAT_ORDER = {
  QB: [
    "crunch_time_grade",
    "completions",
    "attempts",
    "completions_pct",
    "pass_yards",
    "pass_tds",
    "interceptions",
    "sacks",
    "pass_epa",
    "rush_yards",
    "rush_tds",
    "rush_epa",
    "fantasy_points",
    "cpoe",
    "pacr",
    "qbr_total",
    "qbr_epa_total",
  ],
  RB: [
    "crunch_time_grade",
    "carries",
    "rush_yards",
    "rush_tds",
    "rush_fumbles",
    "receptions",
    "rec_yards",
    "rec_tds",
    "rec_fumbles",
    "rec_yac",
    "fantasy_points",
  ],
  WR: [
    "crunch_time_grade",
    "receptions",
    "targets",
    "rec_yards",
    "rec_tds",
    "rec_fumbles",
    "rec_yac",
    "fantasy_points",
    "rec_epa",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",
  ],
  TE: [
    "crunch_time_grade",
    "receptions",
    "targets",
    "rec_yards",
    "rec_tds",
    "rec_fumbles",
    "rec_yac",
    "fantasy_points",
    "rec_epa",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",
  ],
  DB: [
    "crunch_time_grade",
    "solo_tackles",
    "assisted_tackles",
    "tackles_with_assist",
    "tackles_for_loss",
    "fumbles_forced",
    "sacks",
    "qb_hits",
    "interceptions",
    "passes_defended",
    "defensive_tds",
    "penalties",
    "total_tackles",
  ],
};